### ISSUE TITLE
open things in pimo5 instead of swing gui

### ISSUE THREAD

**Issue by svenschwarz** [wagnerand/FireTag#34]
Opening things in FireTag (by double-clicking) should be done in pimo5 now. This is achieved by opening a URL in the (default) browser. The URL depends on the pimo instance, the pattern is as follows:

<baseurl>/pimo5/#res/<uri>

The URI should be URI encoded. Example:

http://pimo.opendfki.de/pimo5/#res/pimo%3A1421024462851%3A1/

**Comment by wagnerand** [comment]
Fixed in f836fa636e724daca2822d3f233beca3e84f53ad.

**Comment by maush** [comment]
in Firetag Sidebar, konnte man früher in die PIMO springen mit "open in pimo". Das ist nun für die annotationen möglich, aber nicht für das Thing selbst. Könnte man entweder in das Kontextmenue (wo schon rename drin ist) machen oder meine Präferenz als Doppelclick auf das Label des Things
