### ISSUE TITLE
scrollbar verdeckt "+"-spalte

### ISSUE THREAD

**Issue by svenschwarz** [wagnerand/FireTag#35]
Wenn scrollbar angezeigt wird, verdeckt diese die spalte zum adden.

**Comment by wagnerand** [comment]
Das Problem ist auf Mac aufgrund des anderen Scrollbar-Designs nicht vorhanden.

Ich weiß nicht, wie ich das beheben soll, außer eine leere Spalte am rechten Rand einzufügen. Andere Ideen?

**Comment by maush** [comment]
Hmm..ist Blocker, deshalb ist eine leere Spalte rechts OK. Alternativ dachte ich mir mal, den plus button nach links zu machen

**Comment by svenschwarz** [comment]
+ buttons lassen sich nicht mehr drücken, oder drücken hat keine wirkung mehr

**Comment by wagnerand** [comment]
Ja, leider war das gar nix...zuviel rumprobiert, mit den Änderungen durcheinander gekommen, nun ist mehr kaputt als vorher... :(

**Comment by wagnerand** [comment]
Fixed.
